name: Deploy CGP

on:
  workflow_call:
    inputs:
      app_host:
        required: true
        type: string
      bucket_name:
        required: false
        type: string
      directory:
        required: false
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      shell: bash
      run: yarn install --production=false
      env:
        NODE_ENV: "production"
        GENERATE_SOURCEMAP: "false"

    - name: Build
      shell: bash
      run: yarn build
      env:
        NODE_ENV: "production"
        FRONT_STG: "production"
        REACT_APP_HOST: "${{ inputs.app_host }}"

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    # - name: Move dist
    #   if: "${{ inputs.directory != '' }}"
    #   shell: bash
    #   run: |
    #     mkdir dist-temp
    #     mv ./dist ./dist-temp/${{ inputs.directory }}
    #     mv ./dist-temp ./dist


    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'dist'
        destination: '${{ inputs.bucket_name }}/${{ inputs.directory }}'
        parent: false
